/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/admin/guilds/{guild_id}/cooldown": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_guild_cooldown"];
		put: operations["set_guild_cooldown"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/guilds/{guild_id}/cooldown/overrides": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_user_overrides"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/guilds/{guild_id}/cooldown/overrides/{user_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["set_user_override"];
		post?: never;
		delete: operations["delete_user_override"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/clips/create/{guild_id}/{channel_id}/{year}/{month}/{file_name}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["create_clip"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/clips/{guild_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_clips"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/clips/{guild_id}/{clip_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations["delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/events/{guild_id}/{channel_id}/{year}/{month}/{stem}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Voice state events (mute/deafen/etc.) overlapping the recording window for
		 *     `{stem}`. Frontend uses `offset_ms` against the audio element's currentTime
		 *     to render markers / current-state badges on the timeline.
		 * @description Bounds: [start_ts, COALESCE(end_ts, now())]. start_ts/end_ts are stored as
		 *     epoch-ms BIGINTs on `audio_files`; voice_state_events.occurred_at is
		 *     TIMESTAMPTZ — converted via `to_timestamp(ms / 1000.0)` for the range scan.
		 */
		get: operations["get_recording_events"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/live/{guild_id}/{channel_id}/{year}/{month}/{stem}/state": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["live_state"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/current/{guild_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_current_month_permission"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/current/{guild_id}/live-stems": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Live recordings for a guild (`audio_files.end_ts IS NULL`), filtered to
		 *     the channels the caller has read access to. Frontend polls this to badge
		 *     the recordings tree. Set is naturally tiny (only currently-active rows).
		 */
		get: operations["get_live_stems"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["logout"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["refresh_jwt"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/remove_silence/{guild_id}/{channel_id}/{year}/{month}/{file_name}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["remove_silence"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/stamps/{guild_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_stamps"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/users/current": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_current_user"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/users/current/guilds": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_current_user_guilds"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ApiError: {
			/** Format: int32 */
			code: number;
			message: string;
		};
		Channels: {
			channel_id: string;
			dirs: components["schemas"]["Directories"][];
		};
		ClipInfo: {
			/** @example 146638124288704513 */
			channel_id: string;
			clip_id: string;
			/** @example 146638124288704513 */
			guild_id: string;
			/** Format: float */
			length?: number | null;
			name?: string | null;
			original_file_name?: string | null;
			saved_file_name?: string | null;
			/** Format: int64 */
			size?: number | null;
			/** Format: float */
			start_time: number;
			/** @example 146638124288704513 */
			user_id: string;
		};
		CooldownBody: {
			/** Format: int32 */
			cooldown_seconds: number;
		};
		CreateClipResponse: {
			file: string;
			id: string;
			name: string;
			status: string;
		};
		Directories: {
			months?: null | components["schemas"]["HashMap"];
			/** Format: int32 */
			year: number;
		};
		File: {
			display_name?: string | null;
			file: string;
			user_id?: string | null;
		};
		GuildCooldown: {
			/** Format: int32 */
			cooldown_seconds: number;
		};
		GuildDataForFrontEnd: {
			icon?: string | null;
			/** @example 146638124288704513 */
			id: string;
			name: string;
			owner: boolean;
			/** @example 268435456 */
			permissions: string;
		};
		HashMap: {
			[key: string]:
				| null
				| {
						display_name?: string | null;
						file: string;
						user_id?: string | null;
				  }[];
		};
		RefreshTokenError: {
			error: string;
			message: string;
		};
		RefreshTokenResponse: {
			token: string;
		};
		RemoveSilenceResponse: {
			message: string;
			url: string;
		};
		StampInfo: {
			/** Format: int64 */
			audio_file_id?: number | null;
			audio_url?: string | null;
			/** @example 146638124288704513 */
			channel_id: string;
			channel_name?: string | null;
			/** Format: date-time */
			created_at: string;
			file_name?: string | null;
			/** @example 146638124288704513 */
			guild_id: string;
			/** Format: int64 */
			id: number;
			/** Format: int32 */
			month?: number | null;
			note?: string | null;
			/** Format: int32 */
			offset_ms: number;
			/** Format: int64 */
			stamp_ts: number;
			stamper_name?: string | null;
			/** @example 146638124288704513 */
			stamper_user_id: string;
			/** Format: int64 */
			start_ts?: number | null;
			target_name?: string | null;
			/** @example 146638124288704513 */
			target_user_id: string;
			waveform_url?: string | null;
			/** Format: int32 */
			year?: number | null;
		};
		StartEnd: {
			/** Format: float */
			end?: number | null;
			name?: string | null;
			/** Format: float */
			start?: number | null;
		};
		StateResponse: {
			/** Format: int64 */
			ended_at?: number | null;
			live: boolean;
			/** Format: int64 */
			started_at?: number | null;
		};
		UserDataForFrontEnd: {
			avatar: string;
			email?: string | null;
			/** Format: int32 */
			flags?: number | null;
			is_dev: boolean;
			/** Format: int32 */
			public_flags?: number | null;
			/** @example 146638124288704513 */
			user_id: string;
			username: string;
		};
		UserOverride: {
			/** Format: int32 */
			cooldown_seconds: number;
			/** Format: date-time */
			updated_at: string;
			/** Format: int64 */
			user_id: number;
		};
		VoiceEventDto: {
			/** Format: int64 */
			channel_id?: number | null;
			event_type: string;
			/** Format: int64 */
			offset_ms: number;
			/** Format: int64 */
			user_id: number;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	get_guild_cooldown: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Guild cooldown */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GuildCooldown"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User is not a guild admin */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	set_guild_cooldown: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CooldownBody"];
			};
		};
		responses: {
			/** @description Guild cooldown updated */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid cooldown */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User is not a guild admin */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	list_user_overrides: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User cooldown overrides */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserOverride"][];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User is not a guild admin */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	set_user_override: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord user id */
				user_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CooldownBody"];
			};
		};
		responses: {
			/** @description User cooldown override updated */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid cooldown */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User is not a guild admin */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	delete_user_override: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord user id */
				user_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User cooldown override deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User is not a guild admin */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	create_clip: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord channel id */
				channel_id: number;
				/** @description Recording year */
				year: number;
				/** @description Recording month */
				month: number;
				/** @description Recording file stem */
				file_name: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["StartEnd"];
			};
		};
		responses: {
			/** @description Clip created */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CreateClipResponse"];
				};
			};
			/** @description Invalid clip request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_clips: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Guild clips */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ClipInfo"][];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Clip id */
				clip_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Clip deleted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Clip not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_recording_events: {
		parameters: {
			query?: {
				/** @description Optional user id filter */
				user_id?: number;
			};
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord channel id */
				channel_id: number;
				/** @description Recording year */
				year: number;
				/** @description Recording month */
				month: number;
				/** @description Recording file stem */
				stem: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Voice events for recording */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["VoiceEventDto"][];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing access or channel permission */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Recording not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	live_state: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord channel id */
				channel_id: number;
				/** @description Recording year */
				year: number;
				/** @description Recording month */
				month: number;
				/** @description Recording file stem */
				stem: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Live recording state */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["StateResponse"];
				};
			};
			/** @description Invalid stem */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_current_month_permission: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Recording tree visible to current user */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Channels"][];
				};
			};
			/** @description Invalid guild id */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Recording directory not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_live_stems: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Currently live recording stems */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": string[];
				};
			};
			/** @description Invalid guild id */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Cookies cleared */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	refresh_jwt: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description New access token issued */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RefreshTokenResponse"];
				};
			};
			/** @description Missing, expired, or invalid refresh token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	remove_silence: {
		parameters: {
			query?: never;
			header: {
				/** @description Idempotency key for processing request */
				"Idempotency-Key": string;
			};
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord channel id */
				channel_id: number;
				/** @description Recording year */
				year: number;
				/** @description Recording month */
				month: number;
				/** @description Recording file stem */
				file_name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Silence removal file exists or processing started */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RemoveSilenceResponse"];
				};
			};
			/** @description Existing processing request completed */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RemoveSilenceResponse"];
				};
			};
			/** @description Missing idempotency key */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Concurrent processing state unavailable */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_stamps: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Recent stamps for guild */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["StampInfo"][];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_current_user: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current authenticated user */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserDataForFrontEnd"];
				};
			};
			/** @description Missing or invalid access_token cookie */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Token not attached to request context */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_current_user_guilds: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Guilds visible to current user */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GuildDataForFrontEnd"][];
				};
			};
			/** @description Token not attached to request context */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
}
